/* DELETE 'deustoCarsDB' database if exists*/
DROP SCHEMA IF EXISTS deustocarsdb;
/* DELETE 'admin' user if exists on the local server*/
DROP USER IF EXISTS 'spq'@'localhost';

/* CREATE 'deustoCarsDB' database*/
CREATE SCHEMA deustocarsdb;
/* CREATE 'spq' user on the local server*/
CREATE USER IF NOT EXISTS 'spq'@'localhost' IDENTIFIED BY 'spq';
/* GIVE 'spq' all permissions*/
GRANT ALL ON deustocarsdb.* TO 'spq'@'localhost';
USE deustocarsdb;

CREATE TABLE `customerjdo` (
  `EMAIL` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `DATEOFBIRTH` timestamp NULL DEFAULT NULL,
  `NAME` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `SURNAME` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  PRIMARY KEY (`EMAIL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `vehiclejdo` (
  `NUMBERPLATE` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `BRAND` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `MODEL` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `ONREPAIR` bit(1) NOT NULL,
  `READYTOBORROW` bit(1) NOT NULL,
  PRIMARY KEY (`NUMBERPLATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `rentingjdo` (
  `PK` int NOT NULL,
  `CUSTOMER_EMAIL_OID` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `ENDDATE` timestamp NULL DEFAULT NULL,
  `STARTDATE` timestamp NULL DEFAULT NULL,
  `VEHICLE_NUMBERPLATE_OID` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  PRIMARY KEY (`PK`),
  KEY `RENTINGJDO_N49` (`VEHICLE_NUMBERPLATE_OID`),
  KEY `RENTINGJDO_N50` (`CUSTOMER_EMAIL_OID`),
  CONSTRAINT `RENTINGJDO_FK1` FOREIGN KEY (`CUSTOMER_EMAIL_OID`) REFERENCES `customerjdo` (`EMAIL`),
  CONSTRAINT `RENTINGJDO_FK2` FOREIGN KEY (`VEHICLE_NUMBERPLATE_OID`) REFERENCES `vehiclejdo` (`NUMBERPLATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `user` (
  `LOGIN` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `ISADMIN` bit(1) DEFAULT NULL,
  `PASSWORD` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  PRIMARY KEY (`LOGIN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci