volumes:
    db_data:

services:
    deustocarsdb:
        container_name: deustocarsdb
        image: mysql:8.4.0
        volumes:
            - db_data:/var/lib/mysql
            - ./sql:/docker-entrypoint-initdb.d
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 30s
            timeout: 10s
            retries: 5

    server:
        container_name: dcserver
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            deustocarsdb:
                condition: service_healthy
        ports:
            - "9080:8080"
        restart: always
        working_dir: /DeustoCars
        environment:
            DB_HOST: deustocarsdb
            DB_USER: ${MYSQL_USER}
            DB_PASSWORD: ${MYSQL_PASSWORD}
            DB_NAME: ${MYSQL_DATABASE}
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080/"]
            interval: 30s
            timeout: 10s
            retries: 5