name: Deustocars CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Clean and compile the project
        run: |
          cd Deustocars
          mvn clean compile

      - name: Start the database
        run: | 
          cd Deustocars/sql
          mysql -u root -p < create-deustoCars.sql
          cd ..
          mvn datanucleus:schema-create
          cd sql
          mysql -u root -p < populate.sql

      - name: Start the server
        run: |
          mvn jetty:run &
          sleep 10

      - name: Run tests and generate reports
        run: |
          mvn test
          mvn jacoco:prepare-agent test jacoco:report
          mvn compile exec:java -Pclient
          mvn compile exec:java -Pserver
          mvn doxygen:report
          mvn validate
