name: Java CI

on:
  push:
    branches:
      - main  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Navigate to project directory
      run: cd C:\Users\Asier\Documents\GitHub\BSPQ23-E7\DeustoCars

    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots package
