name: Java CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Clean and compile
      run: |
        cd Deustocars
        mvn --batch-mode clean compile
    
    - name: Set up database
      run: |
        sudo /etc/init.d/mysql start
        cd Deustocars
        mysql -uroot -proot < sql/create-deustoCars.sql
        mysql -uroot -proot < sql/populate.sql
        mvn --batch-mode --update-snapshots datanucleus:enhance datanucleus:schema-create
        
   
    - name: Run server
      run: |
        cd Deustocars
        mvn --batch-mode jetty:run &
        sleep 25
    
    - name: Run tests
      run: |
        cd Deustocars
        mvn test

