name: Java CI

on:
  push:
    branches: [ main ]
      
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Clean and compile
      run: |
        cd DeustoCars
        mvn --batch-mode clean compile
    
    - name: Set up database
      run: |
        sudo /etc/init.d/mysql start
        cd DeustoCars
        mysql -uroot -proot < sql/create-deustoCars.sql
        mvn --batch-mode --update-snapshots datanucleus:enhance
        mysql -uroot -proot < sql/populate.sql
        
   
    - name: Run server
      run: |
        cd DeustoCars
        mvn --batch-mode jetty:run &
        sleep 20
    
    - name: Run tests
      run: |
        cd DeustoCars
        mvn test


  document:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install doxygen
        run: sudo apt-get install -y doxygen

      - name: Install graphviz
        run: sudo apt-get install -y graphviz

      - name: Generate documentation
        run: |
          cd DeustoCars
          mvn doxygen:report

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: DeustoCars/target/doxygen/html
          publish_branch: gh-pages
          destination_dir: doxygen
          
      - name: Create .nojekyll file
        run: |
          touch DeustoCars/target/doxygen/html/.nojekyll
        continue-on-error: true
      

  package:
    needs: document
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Package the application
        run: |
          cd DeustoCars
          mvn package -DskipTests -DskipITs


